name: Tyecheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: Run typecheck
        uses: mrcjkb/lua-typecheck-action@v1.1.0
        with:
          directories: lua/
          configpath: ".luarc.json"
