name: Lua Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mrcjkb/lua-typecheck-action@v1.1.0
        with:
          directories: lua/
          configpath: ".luarc.json"
